"""cycle_idempotency

Revision ID: 03381356fb13
Revises: 9081ec04c219
Create Date: 2026-09-10 23:00:41.072416
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '03381356fb13'
down_revision: Union[str, Sequence[str], None] = '9081ec04c219'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idempotency_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('actor_id', sa.String(), nullable=False),
    sa.Column('route', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('response', sa.JSON(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'actor_id', 'route', 'key')
    )
    op.create_index(op.f('ix_idempotency_records_organization_id'), 'idempotency_records', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_idempotency_records_organization_id'), table_name='idempotency_records')
    op.drop_table('idempotency_records')
    # ### end Alembic commands ###
